### ISSUE TITLE
Legge til HTML/CSS oppgavene

### ISSUE THREAD

**Issue by arve0** [kodeklubben/kodeklubben.github.io#1]
Finner ikke html/css oppgavene (https://github.com/kodeklubben/oppgaver/tree/master/htmlcss/codeclubUK) her. Hvorfor ikke?

**Comment by Helgenen** [comment]
Oppgavene ligger kun i markdown (.md). De kan oversettes til pdf og html
ved hjelp av et program som Geir Arne Hjelle kjører. Han har brukernavn
@gahjelle på github.

Thu Oct 30 2014 at 12.18.41 skrev Arve Seljebu notifications@github.com:

**Comment by gahjelle** [comment]
Jeg har ikke fått lagt inn html/css-oppgavene eller andre del av CodeClub UK-oppgavene i Scratch som pdf og html.

Grunnen er at jeg ville rydde litt i strukturen for disse kursene slik at de blir konsistente med de andre kursene. Dette har det ikke blitt tid til enda.

Men om det er interesse for å få disse på plass kan jeg prioritere å få dem ut ganske raskt. Det er ikke veldig mye jobb som må gjøres :)

**Comment by arve0** [comment]
Ok. Konsistent med CodeClub UK tenker du?

Hvilken programvare bruker du for å generere HTML og PDF?

**Comment by gahjelle** [comment]
Nei, konsistent med vårt eget opplegg som er ørlite forskjellig fra CodeClub i forhold til mappestruktur og slikt :)

Vi bruker i utgangspunktet Code Club sin lesson_formatter for å parse oppgavene. Per nå kjører jeg med min fork her: https://github.com/gahjelle/lesson_format som har et par oppdateringer i forhold til originalen. Samtidig har Code Club utviklet sin versjon litt videre. Planen er å samkjøre disse igjen etterhvert.

Lesson_format er et pythonprogram som hovedsaklig bruker Pandoc til å konvertere Markdown til HTML, og phantomjs  for å konvertere videre til html.

Et par punkter høyt på prioriteringslista i forhold til denne er automatisk bygging og opplasting når det gjøres endringer i markdown-filene, samt publisering også i et word-vennlig output-format.

**Comment by arve0** [comment]
Flytter denne til kodeklubben/oppgaver
