### ISSUE TITLE
Installasjonsinstruksjoner Python

### ISSUE THREAD

**Issue by okpedersen** [kodeklubben/kodeklubben.github.io#5]
Det var en i dag som lurte på om vi hadde noen installasjonsinstruksjoner for Python på nettsida. Han hadde nemlig hatt litt problemer med å innstallere dette på en (stasjonær) pc hjemme. 

Dette burde vel ikke være så vanskelig å gjøre noe med?

**Comment by arve0** [comment]
Ja, vi burde nok hatt en introduksjon med installasjon (som får med python i path på windows). Flytt denne over til [kodeklubben/oppgaver](//github.com/kodeklubben/oppgaver), så tar vi det der. Dette repoet er kun for å få adressen kodeklubben.github.io (vs kodeklubben.github.io/oppgaver) og det følges ikke av bidragsytere.
