### ISSUE TITLE
Omvisning feiler.

### ISSUE THREAD

**Issue by fuzzy76** [kodeklubben/kodeklubben.github.io#7]
Det er et slags "omvisning"-javascript som tilbyr seg å gi nye besøkende en omvisning. Noen av boblene virket som de omhandlet en annen side (de 2-3 siste), og når omvisningen var ferdig ble jeg dumpet til /undefined.

**Comment by arve0** [comment]
Takk for rapporten! Hvilken nettleser har du?

Feilen er her:
https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/intro.js#L53

eller her:
https://github.com/arve0/codeclub_lesson_builder/blob/master/scripts/intro.js#L149-L155

Sannsynligvis feiler en av disse: Nettleseren din...
- blokkerer cookies
- støtter ikke `window.location.href`

**Comment by fuzzy76** [comment]
Jeg bruker Safari 9.0.3 på OS X (siste utgave).

For å utdype... Først fikk jeg omvisning på forsiden som funket, så fikk jeg omvisning på Python-siden som funket, og så ble jeg sendt tilbake til forsiden og fikk et par bobler som jeg tror egentlig omhandlet noe annet enn det de pekte på, og så ble jeg til slutt sendt til /undefined

**Comment by arve0** [comment]
Skjer det samme om du trykker på omvisningsknappen oppe til høyre?

**Comment by fuzzy76** [comment]
Det skjer fortsatt. Både når den starter automatisk, og når jeg starter den manuelt.

**Comment by arve0** [comment]
Fiksen er ikke deployed enda.

**Comment by arve0** [comment]
Hei! "Fiksen" er deployed, men glemte å høre om det fikset problemet for deg, @fuzzy76?

**Comment by fuzzy76** [comment]
Så godt som. :) Hele omvisningen fungerte utmerket nå, men "gå tilbake der du startet" på slutten gjorde ingenting annet enn å lukke bobla. Jeg ble stående i Python-leksjonen.

**Comment by arve0** [comment]
Ja, det stemmer bra. Den feiler "gracefully". Hvorfor den ikke klarer hente
cookie vet jeg ikke.

**Comment by fuzzy76** [comment]
Ser ut til at den ikke klarer sette cookien i det hele tatt.

**Comment by arve0** [comment]
Sikkerhetsinnstillinger kanskje?

**Comment by fuzzy76** [comment]
Hmm... Tror ikke det. Men jeg registrerer at den verken settes i Safari eller Chrome her. Kun i Firefox.
